### ISSUE TITLE
Missing Dependency `ament_index_cpp` Causes Build Failure in `audio_common` for Music Node

### ISSUE THREAD

**Issue by cdboer** [mgonzs13/audio_common#4]
When attempting to build the audio_common package using `colcon build`, the build process fails with the following error:

```
/path/to/workspace/src/audio_common/audio_common/src/audio_common/music_node.cpp:30:10: fatal error: ament_index_cpp/get_package_share_directory.hpp: No such file or directory
   30 | #include <ament_index_cpp/get_package_share_directory.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Steps to Reproduce:

Clone the repository and navigate to the workspace.

```
git clone <repository-url>
cd <workspace>
```
Run the build command:
```
colcon build
```
The build fails with the error message mentioned above.

I was able to resolve the issue by updating the `CMakeLists.txt` file to include `ament_index_cpp`as a required dependency. The following changes fixed the issue:

Changes in `CMakeLists.txt`:
```cmake
# Added the following line to locate the package
find_package(ament_index_cpp REQUIRED)

# Updated include directories
include_directories(
  include
  ${PORTAUDIO_INCLUDE_DIR}
  ${ament_index_cpp_INCLUDE_DIRS}
)

# Updated dependencies for the target
ament_target_dependencies(music_node rclcpp std_srvs audio_common_msgs ament_index_cpp)
```

Environment:
```
ROS 2 Distro: echo $ROS_DISTRO -> rolling
Ubuntu Version: Ubuntu 24.04
```

Thank you for maintaining this project! Please let me know if you need any further details.

**Comment by mgonzs13** [comment]
@cdboer Thanks for the fix
